### PR TITLE
Update ci cd retrun test on demand

### PR DESCRIPTION
**Pull request by shortSparrow**

### CODE REVIEW

**Review by LeonidShv — APPROVED** [review]

**Comment by shortSparrow** [comment]
rerun test

**Comment by shortSparrow** [comment]
rerun test

**Comment by shortSparrow** [comment]
rerun test

**Comment by shortSparrow** [comment]
'rerun test'

**Comment by shortSparrow** [comment]
rerun test

**Comment by shortSparrow** [comment]
rerurn test

**Comment by shortSparrow** [comment]
rerun test

**Comment by shortSparrow** [comment]
rerun test

**Comment by shortSparrow** [comment]
rerun test

**Comment by shortSparrow** [comment]
rerun test

**Comment by shortSparrow** [comment]
fwfw

**Comment by shortSparrow** [comment]
Hello

**Review by shortSparrow — COMMENTED** [review]
fed

**Comment by shortSparrow** [comment]
Hola

**Review by shortSparrow — COMMENTED** [review]
fw

**Comment by shortSparrow** [comment]
fsfs

**Review by shortSparrow — COMMENTED** [review]
fegeg

**Comment by shortSparrow** [comment]
fwfwx

**Review by shortSparrow — COMMENTED** [review]
ecevge

**Comment by shortSparrow** [comment]
CCC

**Comment by shortSparrow** [comment]
fwfwf

**Comment by shortSparrow** [comment]
fwx

**Comment by shortSparrow** [comment]
fff

**Comment by shortSparrow** [comment]
fff

**Comment by shortSparrow** [comment]
fe

**Comment by shortSparrow** [comment]
xxx

**Review by shortSparrow — COMMENTED** [review]
?d

**Comment by shortSparrow** [comment]
????

**Review by shortSparrow — COMMENTED** [review]
fefefge

**Review by shortSparrow — COMMENTED** [review]
fefeg

**Comment by shortSparrow** [comment]
efefe

**Comment by shortSparrow** [comment]
xxxx

**Comment by shortSparrow** [comment]
gege

**Comment by LeonidShv** [comment]
closed by author recommendations 
@shortSparrow

**Pull request closed without merging**
